# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_FASTR_rcpp_hello_world`)
}

YPR <- function(age, sel, m, mat, wgt, alpha, beta, sigma, inc) {
    .Call(`_FASTR_YPR`, age, sel, m, mat, wgt, alpha, beta, sigma, inc)
}

